[package]
name = "aoc-2021"
version = "0.1.0"
edition = "2021"

[lib]
name = "aoc_2021"

[[bin]]
name = "aoc_bin"
path = "src/main.rs"

[dependencies]

[dev-dependencies]
criterion = "0.3.5"

[[bench]]
name = "star_benchmark"
harness = false